# -*- mode: python; -*-

Import('env')
Import('get_option')

env = env.Clone()

mongofle = env.Program(
    target="mongofle",
    source=[
        "mongofle.cpp",
        "mongofle_commands.cpp",
        "mongofle_options.cpp",
        "mongofle_options_init.cpp"
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/dbmessage',
        '$BUILD_DIR/mongo/rpc/rpc',
        '$BUILD_DIR/mongo/transport/message_compressor',
        '$BUILD_DIR/mongo/transport/service_entry_point',
        '$BUILD_DIR/mongo/transport/service_executor',
        '$BUILD_DIR/mongo/transport/transport_layer',
        '$BUILD_DIR/mongo/util/net/network',
        '$BUILD_DIR/mongo/util/options_parser/options_parser_init',
        '$BUILD_DIR/mongo/util/signal_handlers',
        '$BUILD_DIR/mongo/db/query/query_planner',
    ],
    INSTALL_ALIAS=[
        'tools'
    ],
)


hygienic = get_option('install-mode') == 'hygienic'
if not hygienic:
    env.Install("#/", mongofle)

