# Copyright (C) 2019-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/idl/basic_types.idl"

structs:
    iamClientFirst:
        description: "SASL IAM Client First message"
        fields:
          # Must be 24 bytes
          r:
            type: bindata_generic
            cpp_name: nonce

    iamServerFirst:
        description: "SASL IAM Server First message"
        fields:
          # Must be 24 bytes
          r:
            type: bindata_generic
            cpp_name: nonce
          # Must be 32 bytes
          salt:
            type: bindata_generic
            cpp_name: salt

    iamClientHeaders:
        description: "SASL IAM Client Second message headers"
        fields:
          Content-Length:
            type: string
            cpp_name: contentLength
          Content-Type:
            type: string
            cpp_name: contentType
          Host:
            type: string
          X-Amz-Date:
            type: string
            cpp_name: XAmzDate
          X-Amz-Security-Token:
            type: string
            optional: true
            cpp_name: XAmzSecurityToken
          X-Mongodb-Server-Salt:
            type: string
            cpp_name: XMongodbServerSalt

    iamClientSecond:
        description: "SASL IAM Client Second message"
        fields:
          # Must be 48 bytes
          r:
            type: bindata_generic
            cpp_name: nonce
          h:
            type: iamClientHeaders
            cpp_name: headers
          a:
            type: string
            cpp_name: requestAuthHeader


    Ec2SecurityCredentials:
      description : "foo"
      # Don't fail if AWS expands this
      strict: false
      fields:
          Code: string
          LastUpdated: string
          Type: string
          AccessKeyId: string
          SecretAccessKey: string
          Token:
            type: string
            optional: true
          Expiration: string

