# -*- mode: python -*-
Import("env")

env = env.Clone()

ftdcEnv = env.Clone()
#ftdcEnv.InjectThirdPartyIncludePaths(libraries=['zlib'])

idlc = ftdcEnv.Program(
    target='idlc',
    source=[
        'idl_driver.cpp',
        'idl_options.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/service_context',
        "$BUILD_DIR/mongo/util/signal_handlers",
        "$BUILD_DIR/mongo/util/version_impl",
    ],
)

#env.Alias("all", mongoldap)

ftdcEnv.Install("#/", idlc)

#env.CppUnitTest(
    #target='ftdc_test',
    #source=[
        #'compressor_test.cpp',
    #],
    #LIBDEPS=[
        #'idlc',
    #],
#)
