# -*- mode: python -*-
Import("env")

env = env.Clone()

# idlc = ftdcEnv.Program(
#     target='idlc',
#     source=[
#         'idl_driver.cpp',
#         'idl_options.cpp',
# 		'examples/bikeshed_example.cpp',
#     ],
#     LIBDEPS=[
#         '$BUILD_DIR/mongo/base',
#         '$BUILD_DIR/mongo/db/service_context',
#         "$BUILD_DIR/mongo/util/signal_handlers",
#         "$BUILD_DIR/mongo/util/version_impl",
#         "$BUILD_DIR/mongo/util/options_parser/options_parser_init",
#     ],
# )

env.Library(
    target="idl_parser",
    source=[
        'idl_parser.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ]
)

env.CppUnitTest(
    target='idlstub',
    source=[
        'idl_stub.cpp',
        'idl_test.cpp',
        env.Idlc('unittest.idl')[0]
	],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/idl/idl_parser',
        '$BUILD_DIR/mongo/db/service_context',
        "$BUILD_DIR/mongo/util/signal_handlers",
        "$BUILD_DIR/mongo/util/version_impl",
        "$BUILD_DIR/mongo/util/options_parser/options_parser_init",
    ],
	)
