global:
    cpp_namespace: "mongo"

type:
    name: string
    bson_serialization_type: string 
    cpp_type: "std::string"
    deserializer: "mongo::BSONElement::valueStringData"

struct:
    name: application
    strict: false
    fields:
        name: string

struct:
    name: driver
    strict: false
    fields:
        name: string
        version: string

struct:
    name: os
    fields:
        type: string

struct:
    name: client_metadata
    description: Client Metadata Sample
    fields:
        application: application
        driver: driver
        os : os