global:
    cpp_namespace: "mongo"

type:
    name: string
    bson_serialization_type: string 
    description: string
    cpp_type: "std::string"
    deserializer: "mongo::BSONElement::valueStringData"

struct:
    name: application
    description: client metadata application document
    strict: false
    fields:
        name:
            type: string
            optional: true

struct:
    name: driver
    description: client metadata driver document
    strict: false
    fields:
        name: string
        version: string

struct:
    name: os
    description: client metadata os document
    fields:
        type: string

struct:
    name: client_metadata
    description: Client Metadata Sample
    fields:
        application:
            type: application
            optional: true
        driver: driver
        os : os