# Copyright (C) 2017 MongoDB Inc.
#
# This program is free software: you can redistribute it and/or  modify
# it under the terms of the GNU Affero General Public License, version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# IDL for Client Metadata
global:
    cpp_namespace: "mongo"

type:
    name: string
    bson_serialization_type: string 
    description: string
    cpp_type: "std::string"
    deserializer: "mongo::BSONElement::valueStringData"

struct:
    name: application
    description: client metadata application document
    strict: false
    fields:
        name:
            type: string
            optional: true

struct:
    name: driver
    description: client metadata driver document
    strict: false
    fields:
        name: string
        version: string

struct:
    name: os
    description: client metadata os document
    strict: false
    fields:
        type: string

struct:
    name: client_metadata
    description: Client Metadata Sample
    strict: false
    fields:
        application:
            type: application
            optional: true
        driver: driver
        os : os
